name: Wiki

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update the wiki
        env:
          wiki_key: ${{ secrets.wiki_key }}
        run: |
          git --version
          mkdir -p ~/.ssh/
          echo $wiki_key > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          git push git@github.com:SuperTux/supertux.wiki.git HEAD:master
